### PR TITLE
Support dependency review

### LINKED ISSUE #135: Dependency Review
Does this action work together with GitHub's Dependency Review?

See:
- https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review
- https://github.com/actions/dependency-review-action

### PR DESCRIPTION
**Pull request by johnpangalos**
In order for dependency review to work, we need to compare the github sha for the pull request. This can be read from the context and set it as the GITHUB_SHA env variable when it exists.

Fixes #135

### CODE REVIEW

**Comment by MPV** [comment]
Looks like it works, see:
- https://github.com/MPV/github-dependency-review-for-scala/pull/6

**Review by adpi2 — APPROVED** [review]
LGTM

**Comment by MPV** [comment]
See follow-up PR:
- https://github.com/scalacenter/sbt-dependency-submission/pull/141

**Comment by MPV** [comment]
> Looks like it works, see:
> 
> * [Use `johnpangalos/sbt-dependency-submission` (with PR support) MPV/github-dependency-review-for-scala#6](https://github.com/MPV/github-dependency-review-for-scala/pull/6)
> 
> EDIT: I spoke too soon.

FYI: It works when one runs `npm run all`, as seen in:
- https://github.com/MPV/github-dependency-review-for-scala/pull/7

**Comment by MPV** [comment]
Thank you @adpi2. 
Will you release a new version with this?

**Comment by adpi2** [comment]
Thank you @MPV and @johnpangalos for figuring this out and fixing it. I will cut a release tomorrow morning.

**Comment by MPV** [comment]
Works really well, here's another example:
- https://github.com/MPV/github-dependency-review-for-scala/pull/4

**Comment by MPV** [comment]
>I will cut a release tomorrow morning.

🙏 Thank you

**Pull request merged**
